USE vendas_sucos;
CREATE TABLE itens_notas (
	NUMERO varchar(5) NOT NULL,
    CODIGO varchar(10) NOT NULL,
    QUANTIDADE int,
    PRECO float,
    PRIMARY KEY (NUMERO, CODIGO)
);

ALTER TABLE itens_notas ADD CONSTRAINT FK_NOTAS
FOREIGN KEY (NUMERO) REFERENCES notas (NUMERO);

ALTER TABLE itens_notas ADD CONSTRAINT FK_PRODUTOS
FOREIGN KEY (CODIGO) REFERENCES produtos (CODIGO);