CREATE DEFINER=`root`@`localhost` PROCEDURE `Tabela_Numeros`()
BEGIN
DECLARE CONTADOR INT;
DECLARE CONTMAXIMO INT;
SET CONTADOR = 1;
SET CONTMAXIMO = 100;
DELETE FROM aleatorios;
WHILE CONTADOR <= CONTMAXIMO
DO
INSERT INTO aleatorios (NUMERO) VALUES (NumeroAleatorio(0,1000));
SET CONTADOR = CONTADOR + 1;
END WHILE;
SELECT * FROM aleatorios;
END