create table TABELA_DE_VENDEDORES
(MATRICULA VARCHAR (5),
NOME VARCHAR (100), 
PERCENTUAL_COMISSAO FLOAT);
INSERT INTO TABELA_DE_VENDEDORES
(MATRICULA , NOME , PERCENTUAL_COMISSAO) VALUES ('00233', 'João Geraldo da Fonseca', 0.10);

