CREATE TABLE tab_faturamento (
    DATA_VENDA DATE,
    TOTAL_VENDA FLOAT
);

INSERT INTO notas (NUMERO, DATA_VENDA, CPF, MATRICULA, IMPOSTO)
VALUES ('0100', '2019-05-08', '1471156710', '235', 0.10);

INSERT INTO itens_notas (NUMERO, CODIGO, QUANTIDADE, PRECO)
VALUES ('0100', '1002334', 100, 10);

INSERT INTO notas (NUMERO, DATA_VENDA, CPF, MATRICULA, IMPOSTO)
VALUES ('0101', '2019-05-08', '1471156710', '235', 0.10);

INSERT INTO itens_notas (NUMERO, CODIGO, QUANTIDADE, PRECO)
VALUES ('0101', '1002334', 100, 10);

SELECT * FROM tab_faturamento;

DELIMITER //
CREATE 
    TRIGGER  tg_calcula_faturamento_insert
 AFTER INSERT ON itens_notas FOR EACH ROW 
    BEGIN 
    DELETE FROM tab_faturamento;

INSERT INTO tab_faturamento
SELECT 
    A.DATA_VENDA, SUM(B.QUANTIDADE * B.PRECO) AS TOTAL_VENDAS
FROM
    notas A
        INNER JOIN
    itens_notas B ON A.NUMERO = B.NUMERO
GROUP BY A.DATA_VENDA;
END
//